blank_issues_enabled: true
contact_links:
  - name: Как начать
    url: https://github.com/Micky-52Entertainment/Playable-Testing-Automatisation/blob/main/КАК-НАЧАТЬ.md
    about: Запуск программы и первая проверка
